### ISSUE TITLE
TypeError on import

### ISSUE THREAD

**Issue by havedill** [unfoldingWord-dev/python-gitea-client#21]
``` PS C:\Users\dhill\Git\rival-python-scripts\jobs> python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gogs_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\gogs_client\__init__.py", line 1, in <module>
    from gogs_client.auth import Authentication, Token, UsernamePassword
  File "C:\Program Files\Python37\lib\site-packages\gogs_client\auth.py", line 4, in <module>
    from gogs_client.entities import json_get
  File "C:\Program Files\Python37\lib\site-packages\gogs_client\entities.py", line 84, in <module>
    class GogsRepo(GogsEntity):
  File "C:\Program Files\Python37\lib\site-packages\gogs_client\entities.py", line 105, in GogsRepo
    owner = attr.ib(convert=lambda parsed_json: GogsUser.from_json(parsed_json))
TypeError: attrib() got an unexpected keyword argument 'convert' ```

**Comment by richmahn** [comment]
@havedill I believe it only works with Python v2.7

**Comment by RobH123** [comment]
Oh, that's a problem that comes from the `attrs` package that first deprecated and then eventually dropped `convert`. Setting `attrs==19.1.0` high in the requirements should fix it I think. (I don't know what package is pulling in attrs.)
